#!/usr/bin/env python3
"""
📊 CONTENT KINGDOM DAILY REPORT
Generates end-of-day report: what was posted, which products, which pages
Runs at midnight (00:00) → sends to @Berkahkaryaautosalesbot
"""
import json, subprocess, time
from pathlib import Path
from datetime import datetime, timedelta
from collections import defaultdict

BASE = Path.home()
STATE_FILE = BASE / 'projects/1ai-ads/data/rakdapur_kingdom_state.json'
MAP_FILE = BASE / 'projects/1ai-content/data/rakdapur_video_product_map.json'
PAGES_FILE = BASE / '.openclaw/workspace/data/fb_page_tokens.json'
REPORT_LOG = BASE / 'projects/1ai-ads/logs/kingdom_daily_report.log'

def load_json(path):
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return {}

def generate_report():
    state = load_json(STATE_FILE)
    mapping = load_json(MAP_FILE)
    pages_data = load_json(PAGES_FILE)
    
    today = datetime.now().strftime('%Y-%m-%d')
    
    report = []
    report.append(f"📊 CONTENT KINGDOM REPORT — {today}")
    report.append("=" * 40)
    
    # Summary
    report.append(f"\n📈 TOTAL POSTS: {state.get('total_posts', 0)}")
    report.append(f"🔄 Total runs: {state.get('runs', 0)}")
    report.append(f"⏰ Last run: {state.get('last_run', 'never')}")
    
    # Products assigned per page
    report.append(f"\n📱 PAGE → PRODUCT MAPPING:")
    assigned = state.get('products_assigned', {})
    videos_posted = state.get('videos_posted', {})
    
    page_names = {}
    for pid, data in pages_data.items():
        page_names[pid] = data.get('name', pid[:10])
    
    for pid, prod_ids in assigned.items():
        pname = page_names.get(pid, pid[:12])
        videos = videos_posted.get(pid, [])
        report.append(f"\n{pname} ({pid})")
        report.append(f"   Products assigned: {len(prod_ids)}")
        report.append(f"   Videos posted: {len(videos)}")
        
        # Show last 3 products
        for prod_id in prod_ids[-3:]:
            # Find product details from mapping
            match = None
            for m in mapping:
                if str(m.get('product_id', '')) == str(prod_id) or str(m.get('id', '')) == str(prod_id):
                    match = m
                    break
            if match:
                report.append(f"      🏷️ {match.get('product','?')[:50]}")
                report.append(f"      💰 Rp{match.get('harga',0):,} | Rp{match.get('komisi',0):,}")
    
    # Video asset summary  
    video_dirs = [
        BASE / 'projects/1ai-content/videos/rakdapur/processed',
        BASE / 'projects/1ai-content/videos/kacamatabaca/processed',
    ]
    
    report.append(f"\n🎬 VIDEO ASSETS:")
    for vdir in video_dirs:
        if vdir.exists():
            count = len(list(vdir.glob('*_EDITED.mp4')))
            niche = vdir.parent.name
            size_mb = sum(f.stat().st_size for f in vdir.glob('*_EDITED.mp4')) / 1024 / 1024
            report.append(f"   {niche}: {count} edited videos ({size_mb:.1f}MB)")
    
    # Tomorrow's schedule
    report.append(f"\n⏰ TOMORROW'S SCHEDULE:")
    report.append(f"   08:00 — Morning batch (3 videos)")
    report.append(f"   14:00 — Afternoon batch (3 videos)")  
    report.append(f"   20:00 — Evening batch (3 videos)")
    report.append(f"   Target: 9-15 videos across 15 pages")
    
    # Active niches
    report.append(f"\n🏭 ACTIVE NICHES:")
    report.append(f"   🏠 Rak Dapur — 58 products, 13 videos")
    report.append(f"   👓 Kacamata Baca — 100 products, 8 videos")
    
    report.append(f"\n{'=' * 40}")
    report.append(f"🤖 Auto-generated by Content Kingdom | {datetime.now().strftime('%H:%M')}")
    
    return '\n'.join(report)

def send_to_telegram_bot(report_text, bot_token, chat_id):
    """Send report to Telegram bot"""
    try:
        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        import requests
        r = requests.post(url, json={
            'chat_id': chat_id,
            'text': report_text,
            'parse_mode': 'HTML',
        }, timeout=10)
        return r.json().get('ok', False)
    except Exception as e:
        return str(e)[:100]

if __name__ == '__main__':
    report = generate_report()
    print(report)
    
    # Log to file
    REPORT_LOG.parent.mkdir(parents=True, exist_ok=True)
    with open(REPORT_LOG, 'a') as f:
        f.write(f"\n{'='*60}\n")
        f.write(report)
    
    # Send to bot via OpenClaw message tool (handled by cron wrapper)
    print(f"\n✅ Report generated. Send via: message tool → @Berkahkaryaautosalesbot")
